# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
plugins: [jekyll-paginate, kramdown]

# Setup
title:            Jia Zeng 
tagline:          
description:      'A senior student in Northwestern Polytechnical University.'
url:              http://zjjzeng.github.io
baseurl:          /

author:
  name:           'Jia Zeng'
  url:            https://zjjzeng.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zjjzeng
